name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main  

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push backend/ to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://halhadad:${HF_TOKEN}@huggingface.co/spaces/halhadad/resume-labeling-space
          git subtree split --prefix backend -b backend-deploy
          git push -f hf backend-deploy:main
